---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: amm-techlab
  labels:
    application: amm-techlab
spec:
  kafka:
    version: 2.7.0
    replicas: 1
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    config:
      auto.create.topics.enable: false
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: 2.7
    storage:
      volumes:
      - type: persistent-claim
        size: 10Gi
        id: 0
      type: jbod
    resources:
      limits:
        memory: 4Gi
        cpu: 2
      requests:
        memory: 128Mi
        cpu: 50m
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
    resources:
      limits:
        memory: 4Gi
        cpu: 2
      requests:
        memory: 128Mi
        cpu: 50m
  entityOperator:
    topicOperator: {}
    userOperator: {}
