apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  labels:
    build: spring-boot-bb
  name: wildfly-160-centos7
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: openshift/wildfly-160-centos7
    from:
      kind: DockerImage
      name: openshift/wildfly-160-centos7
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
---  
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  labels:
    build: spring-boot-bb
  name: spring-boot-bb
spec:
  lookupPolicy:
    local: false
