apiVersion: v1
kind: List
metadata:
  labels:
    application: amm-techlab
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        app: data-transformer
        application: amm-techlab
      name: data-transformer
    spec:
      lookupPolicy:
        local: true

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: data-transformer
        application: amm-techlab
      name: data-transformer
    spec:
      replicas: 1
      selector:
        matchLabels:
          deployment: data-transformer
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: data-transformer
            application: amm-techlab
            deployment: data-transformer
        spec:
          containers:
            - image: image-registry.openshift-image-registry.svc:5000/<username>/data-transformer:latest
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 5
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 15
              readinessProbe:
                failureThreshold: 5
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 15
              name: data-transformer
              env:
                - name: kafka.bootstrap.servers
                  value: 'amm-techlab-kafka-bootstrap:9092'
                - name: mp.messaging.incoming.data.connector
                  value: smallrye-kafka
                - name: mp.messaging.incoming.data.topic
                  value: manual
                - name: mp.messaging.incoming.data.value.deserializer
                  value: >-
                    ch.puzzle.quarkustechlab.reactivetransformer.control.SensorMeasurementDeserializer
                - name: transformer.jaeger.enabled
                  value: 'true'
              ports:
              - containerPort: 8080
                name: http
                protocol: TCP
              resources:
                limits:
                  cpu: '1'
                  memory: 500Mi
                requests:
                  cpu: 50m
                  memory: 100Mi

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: data-transformer
        application: amm-techlab
      name: data-transformer
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: http
      selector:
        deployment: data-transformer
      sessionAffinity: None
      type: ClusterIP
