apiVersion: v1
kind: Template
metadata:
  name: secret-s2i-template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: git-credentials
  stringData:
    username: ${USERNAME}
    password: ${PASSWORD}
  type: kubernetes.io/basic-auth
parameters:
- description: AMM techlab participant username
  name: USERNAME
  mandatory: true
- description: AMM techlab participants password
  name: PASSWORD
  mandatory: true