apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-s2i
  name: spring-boot-s2i
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    deploymentconfig: spring-boot-s2i
  sessionAffinity: None
  type: ClusterIP
