apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: quarkus-techlab-data-producer-private
  name: quarkus-techlab-data-producer-private
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: registry.puzzle.ch/puzzle/quarkus-techlab-data-producer-private
    name: latest
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source
