apiVersion: v1
kind: Template
metadata:
  name: route-image-template
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: quarkus-techlab-data-producer-image
    name: quarkus-techlab-data-producer-image
  spec:
    host: ${HOSTNAME}
    port:
      targetPort: http
    tls:
      termination: edge
    to:
      kind: Service
      name: quarkus-techlab-data-producer-image
      weight: 100
    wildcardPolicy: None
parameters:
- description: The public Hostname quarkus-techlab-data-producer-image-${HOSTNAME}.amm-techlab.openshift.ch
  name: HOSTNAME
  mandatory: true