apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-techlab-data-producer-image
  name: quarkus-techlab-data-producer-image
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: quarkus-techlab-data-producer-image
  sessionAffinity: None
  type: ClusterIP
