apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  labels:
    build: quarkus-techlab-data-producer-bb
  name: quarkus-techlab-data-producer-bb
spec:
  output:
    to:
      kind: ImageStreamTag
      name: quarkus-techlab-data-producer-bb:latest
  postCommit: {}
  resources: {}
  source:
    binary: {}
    type: Binary
  strategy:
    type: Docker
  triggers:
  - github:
      secret: u7kQquuC1Hpap8pv82Xz
    type: GitHub
  - generic:
      secret: MduzcwKRw37WrDWWSfCf
    type: Generic
