apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: deploymentconfig-bb-template
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: quarkus-techlab-data-producer-bb
    name: quarkus-techlab-data-producer-bb
  spec:
    replicas: 1
    selector:
      deploymentconfig: quarkus-techlab-data-producer-bb
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          deploymentconfig: quarkus-techlab-data-producer-bb
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/${PROJECT_NAME}/quarkus-techlab-data-producer-bb:latest
          name: quarkus-techlab-data-producer-bb
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - quarkus-techlab-data-producer-bb
        from:
          kind: ImageStreamTag
          name: quarkus-techlab-data-producer-bb:latest
      type: ImageChange
parameters:
- description: OpenShift Project Name
  name: PROJECT_NAME
  required: true
