apiVersion: v1
kind: Template
metadata:
  name: secret-s2i-template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: git-credentials
  stringData:
    username: ${USERNAME}
    password: ${TOKEN}
  type: kubernetes.io/basic-auth
parameters:
- description: AMM techlab participant username
  name: USERNAME
  mandatory: true
- description: Generated access token from Gitea
  name: TOKEN
  mandatory: true
