name: Build user IDE

on:
  push:

jobs:

  build-ide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Get smart tag
        id: prepare
        uses: Surgo/docker-smart-tag-action@v1
        with:
          default_branch: master
          docker_image: quay.io/puzzle/amm-techlab-ide
      -
        name: Define image tag
        run: |
          if [[ "${{ steps.prepare.outputs.tag }}" == *:edge ]]; then
              echo "IDE_IMAGE_TAG=quay.io/puzzle/amm-techlab-ide:latest" >> $GITHUB_ENV
          else
              echo "IDE_IMAGE_TAG=${{ steps.prepare.outputs.tag }}" >> $GITHUB_ENV
          fi
      -
        name: Using image tag
        run: echo ${{ env.IDE_IMAGE_TAG }}
      -
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      -
        name: Build Latest Version
        uses: docker/build-push-action@v2
        with:
          context: ./infra/user-ide
          file: ./infra/user-ide/Dockerfile
          push: true
          tags: ${{ env.IDE_IMAGE_TAG }}
      -
        name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IDE_IMAGE_TAG }}'
          format: 'table'
          output: 'trivy-results.txt'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      -
        name: Archive vulnerability scan results
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results-ide
          path: trivy-results.txt
