name: Build Training

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up npm for linting
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - 
        name: Lint Markdown
        run: npm ci && npm run mdlint
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      - 
        name: Build Latest Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            quay.io/puzzle/amm-techlab:pr-${{ github.event.pull_request.number }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'quay.io/puzzle/amm-techlab:pr-${{ github.event.pull_request.number }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'

      - 
        name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'pr-${{ github.event.pull_request.number }}'
          namespace: 'pitc-amm-techlab-test'
          version: '${{ github.sha }}'
          repository: 'https://acend.github.io/helm-charts/'
          chart: 'acend-training-chart'
          token: '${{ github.token }}'
          helm: 'helm3'
          value-files: |
            [
              "helm-chart/values.yaml"
            ]

        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_TEST }}'
      - 
        name: redeploy puzzle deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_TEST_BASE64 }}
        with:
          args: rollout restart deployment/pr-${{ github.event.pull_request.number }}-amm-techlab-puzzle --namespace pitc-amm-techlab-test
      - 
        name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
           PR Environements: 
           *  puzzle <https://amm-techlab-pr-${{ github.event.pull_request.number }}.k8s.puzzle.ch>

