name: Build user IDE

on:
  push:

jobs:

  build-ide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get smart tag
        id: prepare
        uses: Surgo/docker-smart-tag-action@v1
        with:
          default_branch: master
          docker_image: quay.io/puzzle/amm-techlab-ide
      #-
      #  name: Set up QEMU
      #  uses: docker/setup-qemu-action@v1
      #-
      #  name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v1
      -
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      -
        name: Build Latest Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
      -
        name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.prepare.outputs.tag }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'
