name: Publish Main Version

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up npm for linting
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      -
        name: Lint Markdown
        run: npm ci && npm run mdlint
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      -
        name: Build and Push Latest Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            quay.io/puzzle/amm-techlab:latest
      -
        name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'quay.io/puzzle/amm-techlab:latest'
          format: 'table'
          output: 'trivy-results.txt'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      -
        name: Archive vulnerability scan results
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results-main
          path: trivy-results.txt
      -
        name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'latest'
          namespace: 'pitc-amm-techlab-prod'
          version: '${{ github.sha }}'
          repository: 'https://acend.github.io/helm-charts/'
          chart: 'acend-training-chart'
          token: '${{ github.token }}'
          helm: 'helm3'
          value-files: |
            [
              "helm-chart/values.yaml"
            ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
      -
        name: redeploy puzzle deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_BASE64 }}
        with:
          args: rollout restart deployment/latest-amm-techlab-puzzle --namespace pitc-amm-techlab-prod
