name: Scan for Secrets

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          submodules: false
      - name: Trufflehog Actions Scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: "--regex --max_depth=10 -x .trufflehog/exclude-patterns.txt"