name: Scan for Secrets

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: false
      - name: Trufflehog Actions Scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: "--regex --max_depth=10 -x .trufflehog/exclude-patterns.txt"