name: Scan for Secrets

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          submodules: false
      - name: Trufflehog Actions Scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: "--regex --max_depth=10 -x .trufflehog/exclude-patterns.txt"