name: Scan for Secrets

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          submodules: false
      - name: Trufflehog Actions Scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: "--regex --max_depth=10 -x .trufflehog/exclude-patterns.txt"